### ISSUE TITLE
AVAudioSession not defined

### ISSUE THREAD

**Issue by bradrice** [nstudio/nativescript-audio#149]
I had this working, but the recent nativescript update seems to have broken something on Android:

[30m[31m ERROR [0m ERROR Error: Uncaught (in promise): ReferenceError: AVAudioSession is not defined
ReferenceError: AVAudioSession is not defined
    at file:///data/data/com.toolingu.class2tns/files/app/bundle.js:2749:36
    at ZoneDelegate.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:130972:26)
    at Object.onInvoke (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:67783:33)
    at ZoneDelegate.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:130971:32)
    at Zone.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.Zone.run (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:130722:43)
    at file:///data/data/com.toolingu.class2tns/files/app/vendor.js:131467:34
    at ZoneDelegate.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invokeTask (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:131005:31)
    at Object.onInvokeTask (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:67774:33)
    at ZoneDelegate.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invokeTask (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:131004:36)
    at Zone.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.Zone.runTask (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:130772:47)
    at drainMicroTaskQueue (file:///data/data/com.toolingu.class2tns/files/app/vendor.js:131179:35)

**Comment by bradmartin** [comment]
`AVAudioSession` is for iOS, shouldn't even be executed on Android. This might be a config/build issue though that can have a fix :)

**Comment by bradrice** [comment]
Would there be something I can do to workaround? I have built a player and it has a scrub bar to show the location using Progress. However, on Android it isn't working, I think because this error is being thrown when the audio starts. It is playing the audio, just not allowing js beyond the start.

**Comment by bradrice** [comment]
Never mind. I had to make this conditional:

if(this._player.ios){
                    const audioSession = AVAudioSession.sharedInstance();
                    audioSession.setCategoryError(AVAudioSessionCategoryPlayback);
                }

**Comment by bradmartin** [comment]
glad you sorted it, just odd that Android would even be aware of the `AVAudioSession`, maybe we have a bug in the source that's not wrapped in platform check or in the wrong os file.

I eventually plan to scrap this plugin and isolate the `player` and `recorder` to simplify the plugins and to make iOS streaming improvements so I'll be sure to look at this when I get around to it. Might be few weeks tho.

**Comment by bradrice** [comment]
Thanks for your work on this. Generally, it works great. Looking forward to the next iteration.
